config/routes.rb
Lgdpm::Application.routes.draw do
  
  devise_for :users, :controllers => { :sessions => 'users', :omniauth_callbacks => 'omniauth_callbacks', :registrations => 'registrations' }
  
  root :to => 'evacuees#index'
  
  match "evacuees/index"       => "evacuees#index",       :via => :get
  match "evacuees/search"      => "evacuees#search",      :via => :get
  match "evacuees/search"      => "evacuees#search",      :via => :post
  match "evacuees/new"         => "evacuees#new",         :via => :get
  match "evacuees"             => "evacuees#create",      :via => :post
  match "evacuees/:id/edit"    => "evacuees#edit",        :via => :get, :as => "evacuees_edit"
  match "evacuees/:id"         => "evacuees#update",      :via => :put
  
  match "jukis/index"          => "jukis#index",          :via => :get
  match "jukis/import"         => "jukis#import",         :via => :post
  
  match "autocomplete/city"   => "application#autocomplete_city",   :via => :get
  match "autocomplete/street" => "application#autocomplete_street", :via => :get
  
  match "shelters"            => "application#shelters", :via => :get
  match "address"             => "application#address" , :via => :get
  match "master"              => "application#master"  , :via => :get
  
  mount Resque::Server, at: "/resque"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t("label_title") %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="wrapper">
      <div id="wrapper2">
        <div id="top-menu">
          <div id="account">
            <ul>
              <li>
                <%= link_to "ログアウト", destroy_user_session_path %>
              </li>
            </ul>
          </div>
          <div id="loggedas">
            ログイン中： <%= link_to current_user.login, "#" %>
          </div>
        </div>
        <% if @run_mode_announce.present? %>
          <div style="background: red; padding: 3px;">
            <%= @run_mode_announce %>
          </div>
        <% end %>
        <div id="header">
          <h1><%= t("label_title") %></h1>
          <div id="quick-search"></div>
          <div id="main-menu">
            <%= tabs_tag(:builder => MenuTabBuilder) do |tab| %>
              <%= tab.evacuee t("label_tab_evacuee"), evacuees_index_path %>
              <%= tab.register t("label_tab_register"), evacuees_new_path %>
              <% if current_user.provider.nil? || (current_user.provider != "ldap") %>
                <% if admin_user_flg() %>
                  <%= tab.juki t("label_tab_juki"), jukis_index_path %>
                <% end %>
              <% else %>
                <% if ldap_juki_tab_flg() %>
                  <%= tab.juki t("label_tab_juki"), jukis_index_path %>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
        <div id="main" class="nosidebar">
          <div id="sidebar"></div>
          <div id="content">
            <% if alert %>
              <div class="flash error"><%= alert %></div>
            <% end %>
            <% if notice %>
              <div class="flash notice"><%= notice %></div>
            <% end %>
            <%= yield %>
          </div>
        </div>
      </div>
       <div id="footer">
          <div class="bgl">
            <div class="bgr">
              <%= SETTINGS["version"] %>
            </div>
          </div>
        </div>
    </div>
  </body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= I18n.t("label_title") %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="wrapper">
      <div id="wrapper2">
        <div id="top-menu"></div>
        <div id="header">
          <h1 class="login"><%= I18n.t("label_title") %></h1>
          <div id="quick-search"></div>
          <div id="main-menu"></div>
        </div>
        <div id="main" class="nosidebar">
        <% if @run_mode_announce.present? %>
          <div style="background: red; padding: 3px;">
            <%= @run_mode_announce %>
          </div>
        <% end %>
          <div id="sidebar"></div>
          <div id="content">
            <% if alert %>
              <div class="flash error"><%= alert %></div>
            <% end %>
            <% if notice %>
              <div class="flash notice"><%= notice %></div>
            <% end %>
            <%= yield %>
            <div class="footer">
              <%= SETTINGS["version"] %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>