config/routes.rb
Lgdpm::Application.routes.draw do
  
  devise_for :users, :controllers => { :sessions => 'users', :omniauth_callbacks => 'omniauth_callbacks', :registrations => 'registrations' }
  
  root :to => 'evacuees#index'
  
  match "evacuees/index"       => "evacuees#index",       :via => :get
  match "evacuees/search"      => "evacuees#search",      :via => :get
  match "evacuees/search"      => "evacuees#search",      :via => :post
  match "evacuees/new"         => "evacuees#new",         :via => :get
  match "evacuees"             => "evacuees#create",      :via => :post
  match "evacuees/:id/edit"    => "evacuees#edit",        :via => :get, :as => "evacuees_edit"
  match "evacuees/:id"         => "evacuees#update",      :via => :put
  
  match "jukis/index"          => "jukis#index",          :via => :get
  match "jukis/import"         => "jukis#import",         :via => :post
  
  match "autocomplete/city"   => "application#autocomplete_city",   :via => :get
  match "autocomplete/street" => "application#autocomplete_street", :via => :get
  
  match "shelters"            => "application#shelters", :via => :get
  match "address"             => "application#address" , :via => :get
  match "master"              => "application#master"  , :via => :get
  
  mount Resque::Server, at: "/resque"
end

app/controllers/evacuees_controller.rb
# -*- coding:utf-8 -*-
# 避難者の管理、住基情報とのマッチングを行う
class EvacueesController < ApplicationController
  # タブリンクのカレントタブ制御に使用
  set_tab :evacuee
  set_tab :register, :only => [:new, :create]

  # 避難者一覧画面
  # 初期表示処理
  # ==== Args
  # _search_ :: 画面入力された検索条件
  # _page_ :: ページ番号
  # ==== Return
  # ==== Raise
  def index

    if !params.nil? and !params[:search].nil? and !params[:search][:meta_sort].nil? then

        meta_sort = params[:search][:meta_sort]
        meta_sort_array = meta_sort.split(".")

        if meta_sort_array[0] == "shelter_name" then
          convert_null_value = "''"

          params[:search].delete('meta_sort')
          @search   = Evacuee.mode_in().search(params[:search])
          @evacuees = @search.order("CASE WHEN #{meta_sort_array[0]} IS NULL THEN #{convert_null_value} ELSE #{meta_sort_array[0]} END #{meta_sort_array[1]}").order(:alternate_family_name, :alternate_given_name).paginate(:page => params[:page])

          #退避させておいた状態を元に戻す
          params[:search]['meta_sort'] = meta_sort
          @search   = Evacuee.mode_in().search(params[:search])
        elsif meta_sort_array[0] == "alternate_family_name_and_alternate_given_name" then
          convert_null_value = "''"
          meta_sort_title_array = meta_sort_array[0].split("_and_")

          params[:search].delete('meta_sort')
          @search   = Evacuee.mode_in().search(params[:search])
          @evacuees = @search.order("CASE WHEN #{meta_sort_title_array[0]} IS NULL THEN #{convert_null_value} ELSE #{meta_sort_title_array[0]} END #{meta_sort_array[1]}").order("CASE WHEN #{meta_sort_title_array[1]} IS NULL THEN #{convert_null_value} ELSE #{meta_sort_title_array[1]} END #{meta_sort_array[1]}").order(:alternate_family_name, :alternate_given_name).paginate(:page => params[:page])

          #退避させておいた状態を元に戻す
          params[:search]['meta_sort'] = meta_sort
          @search   = Evacuee.mode_in().search(params[:search])
        elsif meta_sort_array[0] == "home_state_and_home_city_and_home_street_and_house_number" then
          convert_null_value = "''"
          meta_sort_title_array = meta_sort_array[0].split("_and_")

          params[:search].delete('meta_sort')
          @search   = Evacuee.mode_in().search(params[:search])
          @evacuees = @search.order("CASE WHEN #{meta_sort_title_array[0]} IS NULL THEN #{convert_null_value} ELSE #{meta_sort_title_array[0]} END #{meta_sort_array[1]}").order("CASE WHEN #{meta_sort_title_array[1]} IS NULL THEN #{convert_null_value} ELSE #{meta_sort_title_array[1]} END #{meta_sort_array[1]}").order("CASE WHEN #{meta_sort_title_array[2]} IS NULL THEN #{convert_null_value} ELSE #{meta_sort_title_array[2]} END #{meta_sort_array[1]}").order("CASE WHEN #{meta_sort_title_array[3]} IS NULL THEN #{convert_null_value} ELSE #{meta_sort_title_array[3]} END #{meta_sort_array[1]}").order(:alternate_family_name, :alternate_given_name).paginate(:page => params[:page])

          #退避させておいた状態を元に戻す
          params[:search]['meta_sort'] = meta_sort
          @search   = Evacuee.mode_in().search(params[:search])
        else
          @search   = Evacuee.mode_in().search(params[:search])
          @evacuees = @search.order(:alternate_family_name, :alternate_given_name).paginate(:page => params[:page])
        end

    else
        @search   = Evacuee.mode_in().search(params[:search])
        @evacuees = @search.order(:alternate_family_name, :alternate_given_name).paginate(:page => params[:page])
    end

    render :action => :index
  end

  # 避難者一覧画面
  # 検索処理
  # 押下されたボタンにより、処理を分岐する
  # * 検索ボタンが押下された場合、検索を行い自画面に遷移する
  # * PFから取込ボタンが押下された場合、PFから避難者情報を取り込む
  # * PFへ出力ボタンが押下された場合、PFへ避難者情報を出力する
  # * 避難者名簿印刷ボタンが押下された場合、検索を行い避難所単位に避難者情報をPDF出力する
  # * 避難所一覧に出力ボタンが押下された場合、避難者情報を集計しLGDISへ出力する
  # * その他の場合、例外を発生させる
  # ==== Args
  # _commit_kind_ :: ボタン種別
  # ==== Return
  # ==== Raise
  def search
    case params[:commit_kind]
    when "search" # 検索ボタン
      index
    when "pf_import" # PFから取込ボタン
      pf_import
    when "pf_export" # PFへ出力ボタン
      pf_export
    when "print" # 避難者名簿印刷ボタン
      print
    when "total" # 避難所一覧に出力ボタン
      total
    else # その他
      index
    end
  end

  # 避難者一覧画面
  # PF避難者情報取込処理
  # ==== Args
  # ==== Return
  # ==== Raise
  def pf_import
    # 非同期でインポート処理を実行する
    flash.now[:notice] = t("notice_start_pf_import")
    Resque.enqueue(PfImportJob)
    index
  end

  # 避難者一覧画面
  # PF避難者情報出力処理
  # ==== Args
  # ==== Return
  # ==== Raise
  def pf_export
    Evacuee.exec_pf_export(Evacuee.mode_in(), current_user)
    flash.now[:notice] = t("notice_successful_pf_export")

  rescue ActiveResource::ServerError => e
    flash.now[:alert] = "#{e}"
  rescue Errno::ECONNREFUSED
    flash.now[:alert] = t("errors.messages.connection_refused")
  ensure
    index
  end

  # 避難者一覧画面
  # 印刷処理
  # 検索条件に合致する避難者情報を全件PDFに出力する
  # ==== Args
  # _search_ :: 画面入力された検索条件
  # _page_ :: ページ番号
  # ==== Return
  # ==== Raise
  def print
    require 'nkf'
    # 外部へ公開に同意している避難者のみ出力する
    @search   = Evacuee.mode_in().where(:public_flag => Evacuee::PUBLIC_FLAG_ON).search(params[:search])
    @evacuees = @search.paginate(:page => params[:page])
    # 避難者情報が存在しない場合、出力しない
    if @evacuees.blank?
      flash.now[:alert] = t("errors.messages.evacuees_not_exists")
      render :action => :index
      return
    end
    # 避難者を避難所単位に分ける
    evacuees_list = {}
    @search.each do |evacuee|
      shelter = LocalShelter.hash_for_table[evacuee.shelter_name]
      shelter_name = (shelter.blank? ? "避難所なし" : shelter)
      evacuees_list[shelter_name] = {} unless evacuees_list[shelter_name]
      evacuees_list[shelter_name][evacuee.id] = evacuee
    end
    # 避難所単位でpdfを生成する
    reports = {}
    evacuees_list.each_pair do |shelter_name, evacuees_hash|
      report = ThinReports::Report.new layout: File.join(Rails.root, 'lib', 'evacuees_list.tlf')
      # ヘッダー部の設定
      report.list(:evacuees_list).header do |h|
        h.item(:shelter_name).value(shelter_name)
      end
      # 明細部の設定
      evacuees_hash.each_pair do |id, evacuee|
        report.list(:evacuees_list).add_row do |row|
          row.values name:               "#{evacuee.family_name} #{evacuee.given_name}",
                     name_kana:          "#{evacuee.alternate_family_name} #{evacuee.alternate_given_name}",
                     address:            "#{@state[evacuee.home_state]}#{evacuee.home_city}#{evacuee.home_street}#{evacuee.house_number}",
                     date_of_birth:      (evacuee.date_of_birth.present? ? evacuee.date_of_birth.strftime("%Y/%m/%d") : ""),
                     age:                evacuee.age,
                     shelter_entry_date: (evacuee.shelter_entry_date.present? ? evacuee.shelter_entry_date.strftime("%Y/%m/%d") : ""),
                     shelter_leave_date: (evacuee.shelter_leave_date.present? ? evacuee.shelter_leave_date.strftime("%Y/%m/%d") : ""),
                     next_place:         evacuee.next_place
        end
      end
      reports[shelter_name] = report
    end
    # pdfを生成する
    files = {}
    reports.each_pair do |shelter_name, report|
      files[NKF.nkf('-sxm0', "#{shelter_name}.pdf")] = report.generate
    end
    # 生成されたpdfをzipで圧縮する
    buf = ''
    Zip::Archive.open_buffer(buf, Zip::CREATE) do |archive|
      files.each_pair do |filename, filestream|
        archive.add_buffer(NKF.nkf('-sxm0', filename), filestream)
      end
    end
    # IEでのファイルダウンロードの際の文字化け対策
    ie_download_name = "避難者一覧"
    ie_download_name = ERB::Util.url_encode(ie_download_name) if /MSIE/ =~ request.user_agent
    # zipを出力する
    send_data(buf, filename: ie_download_name + "_#{Time.now.instance_eval {'%s%06d' % [strftime('%Y%m%d%H%M%S'),usec]}}.zip",
      type: "application/zip", disposition: "attached")
  end

  # 避難者一覧画面
  # 集計処理
  # 避難者情報を集計しLGDISに連携する
  # ==== Args
  # ==== Return
  # ==== Raise
  def total
    # ルーティング上プロジェクト識別子が必要
    project_identifier = SETTINGS["activeresource"]["lgdis"]["project_identifier"]
    shelters = Shelter.find(:all, :params => { project_id: project_identifier })

    summary = Hash.new
    Evacuee.mode_in().find_for_count.each do |result|
      summary[result.shelter_name] = result
      # 避難所識別番号が一致する避難所を取得
      #index = shelters.rindex{|s| 
      #  p s.shelter_code
      #  s.shelter_code == result.shelter_name 
      #}
      #next if index.blank?
      #shelter = shelters[index]
      # 人数（自主避難人数を含む）
      #shelter.head_count = result["head_count"]
      # 世帯数（自主避難世帯数を含む）
      # shelter.households = result["households_count"]
      # 負傷_計
      #shelter.injury_count = result["injury_flag_count"]
      # 要介護度_計
      #shelter.upper_care_level_three_count = result["upper_care_level_three_count"]
      # 一人暮らし高齢者（65歳以上）_計
      #shelter.elderly_alone_count = result["elderly_alone_count"]
      # 高齢者世帯（夫婦共に65歳以上）_計
      #shelter.elderly_couple_count = result["elderly_couple_count"]
      # 寝たきり高齢者_計
      #shelter.bedridden_elderly_count = result["bedridden_elderly_count"]
      # 認知症高齢者_計
      #shelter.elderly_dementia_count = result["elderly_dementia_count"]
      # 療育手帳所持者_計
      #shelter.rehabilitation_certificate_count = result["rehabilitation_certificate_count"]
      # 身体障害者手帳所持者_計
      #shelter.physical_disability_certificate_count = result["physical_disability_certificate_count"]
      # 不要データを削除
      #shelter.attributes.delete(:created_at)
      #shelter.attributes.delete(:updated_at)
      #shelter.attributes.delete(:deleted_at)
      #shelter.attributes.delete(:record_mode)

      #shelter.save
    end

    shelters.each do |shelter|
      if summary.include?(shelter.shelter_code)
        result = summary[shelter.shelter_code]
        # 人数（自主避難人数を含む）
        shelter.head_count = result["head_count"]
        # 世帯数（自主避難世帯数を含む）
        shelter.households = result["households_count"]
        # 負傷_計
        shelter.injury_count = result["injury_flag_count"]
        # 要介護度_計
        shelter.upper_care_level_three_count = result["upper_care_level_three_count"]

app/helpers/evacuees_helper.rb
module EvacueesHelper
  
end

app/views/evacuees/_form.html.erb
<%= hidden_field_tag "commit_kind" %>

<%= javascript_tag do %>
  $(function(){
    $( "#evacuee_home_city" ).autocomplete({
      source: function(request, response) {
        $.ajax({
          url: <%= raw "\"#{autocomplete_city_path}\"" %>,
          dataType: "json",
          data: {
            term: request.term,
            state: $('#evacuee_home_state').val()
          },
          success: function(data) {
            response(data);
          }
        });
      },
      minLength: 1
    });
    
    $( "#evacuee_home_street" ).autocomplete({
      source: function(request, response) {
        $.ajax({
          url: <%= raw "\"#{autocomplete_street_path}\"" %>,
          dataType: "json",
          data: {
            term: request.term,
            state: $('#evacuee_home_city').val()
          },
          success: function(data) {
            response(data);
          }
        });
      },
      minLength: 1
    });
  });
<% end %>

<div style="background-color: #ADD8E6; padding: 10px;">
  <h2 style="display: inline;">避難者登録・更新</h2>
</div>

<div class="box tabular">
  <div id="all_attributes">
    
    <%= error_messages_for(@evacuee) %>
    
    <div class="splitcontent">
      <div class="splitcontentleft">
        
      </div>
      <div class="splitcontentright">
        <p style="float: right;">
          <%= submit_tag "保存", :kind => "save", :confirm => I18n.t(:text_save_confirmation),  :tabindex => 33 %>
          <%= submit_tag "削除", :kind => "delete", :disabled => @evacuee.new_record?, :confirm => I18n.t("text_destroy_confirmation"), :tabindex => 34 %>
          <%= submit_tag "戻る", :kind => "back", :tabindex => 35 %>
        </p>
      </div>
    </div>

    <div class="splitcontent">
      <div class="splitcontentleft">
        <p>
         <label id="nameid">氏名</label>
         <label style="color:red">*</label>
          <%= text_field :evacuee, :family_name, :size => 15, :tabindex => 1 %>
          <%= text_field :evacuee, :given_name, :size => 15, :tabindex => 2 %>
        </p>
        <p style="width: 360px;">
          <label>生年月日</label>
          <%= text_field :evacuee, :date_of_birth, :tabindex => 5 %>
        </p>
        <p>
          <label>郵便番号</label>
          <%= text_field :evacuee, :home_postal_code, :tabindex => 7 %>
        </p>
        <p>
          <label>都道府県</label>
          <%= select(:evacuee, :home_state,
          options_for_select(@state.invert,
          @evacuee.home_state),
          { :include_blank => true }, :tabindex => 9) %>
        </p>
        <p>
          <label>町名</label>
          <%= text_field :evacuee, :home_street, :tabindex => 11 %>
        </p>
        <p>
          <label>避難所</label>
          <%= select(:evacuee, :shelter_name,
          options_for_select(@shelter.invert,
          @evacuee.shelter_name),
          { :include_blank => true }, :tabindex => 13) %>
        </p>
      </div>
      <div class="splitcontentright">
        <p>
          <label>氏名カナ</label>
          <%= text_field :evacuee, :alternate_family_name, :size => 15, :tabindex => 3 %>
          <%= text_field :evacuee, :alternate_given_name, :size => 15, :tabindex => 4 %>
        </p>
        <p>
          <label>性別</label>
          <%= select(:evacuee, :sex,
          options_for_select(@evacuee_const["sex"].invert, @evacuee.sex),
          { :include_blank => true }, :tabindex => 6) %>
        </p>
        <p>
          <label>年齢</label>
          <%= text_field :evacuee, :age, :size => 15, :tabindex => 8 %>
        </p>
        <p>
          <label>市区町村</label>
          <%= text_field :evacuee, :home_city, :tabindex => 10 %>
        </p>
        <p>
          <label>番地</label>
          <%= text_field :evacuee, :house_number, :tabindex => 12 %>
        </p>
        <p>
          <label>避難状況</label>
          <%= select(:evacuee, :refuge_status,
          options_for_select(@evacuee_const["refuge_status"].invert,
          @evacuee.refuge_status),
          { :include_blank => true }, :tabindex => 14) %>
        </p>
      </div>
    </div>
    
    <p>
      <label>避難理由</label>
      <%= text_area :evacuee, :refuge_reason, :tabindex => 15, :size => "80x3" %>
    </p>
    
    <div class="splitcontent">
      <div class="splitcontentleft">
        <p>
          <label>入所年月日</label>
          <%= text_field :evacuee, :shelter_entry_date, :tabindex => 16 %>
        </p>
        <p>
          <label>退所先</label>
          <%= text_field :evacuee, :next_place, :tabindex => 18 %>
        </p>
      </div>
      <div class="splitcontentright">
        <p>
          <label>退所年月日</label>
          <%= text_field :evacuee, :shelter_leave_date, :tabindex => 17 %>
        </p>
        <p>
          <label>退所先電話番号</label>
          <%= text_field :evacuee, :next_place_phone, :tabindex => 19 %>
        </p>
      </div>
    </div>
    
    <p>
      <label>負傷内容</label>
      <%= text_area :evacuee, :injury_condition, :tabindex => 20, :size => "80x3" %>
    </p>
    <p>
      <label>アレルギー物質</label>
      <%= text_area :evacuee, :allergy_cause, :tabindex => 21, :size => "80x3" %>
    </p>
    
    <div class="splitcontent">
      <div class="splitcontentleft">
        <p>
          <label>妊婦</label>
          <%= select(:evacuee, :pregnancy,
          options_for_select(@evacuee_const["pregnancy"].invert, @evacuee.pregnancy),
          :tabindex => 22) %>
        </p>
        <p>
          <label>要介護度</label>
          <%= select(:evacuee, :upper_care_level_three,
          options_for_select(@evacuee_const["upper_care_level_three"].invert,
          @evacuee.upper_care_level_three),
          :tabindex => 24) %>
        </p>
        <p>
          <label>高齢者世帯（夫婦共に65歳以上）</label>
          <%= select(:evacuee, :elderly_couple,
          options_for_select(@evacuee_const["elderly_couple"].invert,
          @evacuee.elderly_couple),
          :tabindex => 26) %>
        </p>
        <p>
          <label>認知症高齢者</label>
          <%= select(:evacuee, :elderly_dementia,
          options_for_select(@evacuee_const["elderly_dementia"].invert,
          @evacuee.elderly_dementia),
          :tabindex => 28) %>
        </p>
        <p>
          <label>身体障害者手帳所持者</label>
          <%= select(:evacuee, :physical_disability_certificate,
          options_for_select(@evacuee_const["physical_disability_certificate"].invert,
          @evacuee.physical_disability_certificate),
          :tabindex => 30) %>
        </p>
        <p>
          <label>外部に公開</label>
          <%= radio_button_tag "evacuee[public_flag]", Evacuee::PUBLIC_FLAG_ON, (@evacuee.public_flag == Evacuee::PUBLIC_FLAG_ON ? true : false) %>
          <%= label :evacuee, "public_flag_#{Evacuee::PUBLIC_FLAG_ON}", "はい", :style => "float:none;margin:0;font-weight:normal;" %>
          <%= radio_button_tag "evacuee[public_flag]", Evacuee::PUBLIC_FLAG_OFF, (@evacuee.public_flag == Evacuee::PUBLIC_FLAG_OFF ? true : false) %>
          <%= label :evacuee, "public_flag_#{Evacuee::PUBLIC_FLAG_OFF}", "いいえ", :style => "float:none;margin:0;font-weight:normal;" %>
        </p>
      </div>
      
      <div class="splitcontentright">
        <p>
          <label>乳幼児</label>
          <%= select(:evacuee, :baby,
          options_for_select(@evacuee_const["baby"].invert, @evacuee.baby),
          :tabindex => 23) %>
        </p>
        <p>
          <label>一人暮らし高齢者（65歳以上）</label>
          <%= select(:evacuee, :elderly_alone,
          options_for_select(@evacuee_const["elderly_alone"].invert,
          @evacuee.elderly_alone),
          :tabindex => 25) %>
        </p>
        <p>
          <label>寝たきり高齢者</label>
          <%= select(:evacuee, :bedridden_elderly,
          options_for_select(@evacuee_const["bedridden_elderly"].invert,
          @evacuee.bedridden_elderly),
          :tabindex => 27) %>
        </p>
        <p>
          <label>療育手帳所持者</label>
          <%= select(:evacuee, :rehabilitation_certificate,
          options_for_select(@evacuee_const["rehabilitation_certificate"].invert,
          @evacuee.rehabilitation_certificate),
          :tabindex => 29) %>
        </p>
        <p>
          <label>家族も無事</label>
          <%= check_box :evacuee, :family_well, :tabindex => 31 %>
        </p>
      </div>
    </div>
    
    <p>
      <label>備考</label>
      <%= text_area :evacuee, :note, :tabindex => 32, :size => "80x3" %>
    </p>

  </div>
</div>

<strong>家族一覧</strong>
<table class="list">
  <thead>
    <tr>
      <th class="set_center">氏名</th>
      <th class="set_center">氏名カナ</th>
      <th class="set_center">性別</th>
      <th class="set_center">生年月日</th>
      <th class="set_center">住所</th>
      <th class="set_center">筆頭者</th>
    </tr>
  </thead>
  <tbody>
    <% @jukis.each do |juki| %>
      <tr class="<%= cycle("even", "odd") -%>">
        <td class="set_center">
          <%= "#{juki.family_name} #{juki.given_name}" %>
        </td>
        <td class="set_center">
          <%= "#{juki.alternate_family_name} #{juki.alternate_given_name}" %>
        </td>
        <td class="set_center">
          <%= @evacuee_const["sex"][juki.sex] %>
        </td>
        <td class="set_center">
          <%= l(juki.date_of_birth) if juki.date_of_birth.present? %>
        </td>
        <td class="set_center">
          <%= "#{juki.home_state}#{juki.home_city}#{juki.home_street}#{juki.house_number}" %>
        </td>
        <td class="set_center">
          <%= juki.family_head %>
        </td>
      </tr>
    <% end if @jukis.present? %>
  </tbody>
</table>

app/views/evacuees/edit.html.erb
<%= form_tag({:action => :update}, {:method => :put}) do %>
  <%= hidden_field :evacuee, :updated_by, :value => current_user.login %>
  <%= render 'form' %>
<% end %>

app/views/evacuees/new.html.erb
<%= form_tag({:action => :create}, {:method => :post}) do %>
  <%= hidden_field :evacuee, :created_by, :value => current_user.login %>
  <%= hidden_field :evacuee, :updated_by, :value => current_user.login %>
  <%= render 'form' %>
<% end %>